<?php
/*
Common Variables are difined here

*/

$_EMAILFROM = "info@lms.com";
//$_DOMAINNAME = "lms.com";
$_DOMAINNAME = "";
$_SQLINJECTIONPATTERN = array("UNION ALL","INTO OUTFILE","LOAD_FILE","INFORMATION_SCHEMA","SHOW TABLES","SHOW DATABASES"," CHAR(","@@VERSION","-999.9","-9.9","x=x","x=y","WAITFOR DELAY"," hex(","(1=1"," 1=1"," DATABASE(");
$_ADMINEMAIL = "jeevanantham.n@gmail.com";
$_LOGFILEPATH = "/var/log/";

$_USERTYPES = array(1=>"Administrator",3=>"Store Man",4=>"Driver",5=>"Supervisor");
$_MEASUREMENTS = array(1=>"Unit",2=>"Ltr");




?>
